
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


/home/hf1/.conda/envs/hf_diff_apf/lib/python3.12/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "
  0%|          | 0/185 [00:00<?, ?it/s]  0%|          | 0/185 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/home/hf1/Documents/DNNAutoAlign/train_auto_align.py", line 192, in <module>
    train(ann, "/home/hf1/Documents/RLAutoAlign/soundfiles/SDDS_segmented_Allfiles", use_gpu=use_gpu)
  File "/home/hf1/Documents/DNNAutoAlign/train_auto_align.py", line 119, in train
    p_hat = net(input_x, target_y)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hf1/.conda/envs/hf_diff_apf/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hf1/.conda/envs/hf_diff_apf/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hf1/Documents/DNNAutoAlign/model.py", line 77, in forward
    input_data = block(input_data)
                 ^^^^^^^^^^^^^^^^^
  File "/home/hf1/.conda/envs/hf_diff_apf/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hf1/.conda/envs/hf_diff_apf/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hf1/Documents/DNNAutoAlign/gtnc_model.py", line 55, in forward
    x_conv = self.conv1(x)
             ^^^^^^^^^^^^^
  File "/home/hf1/.conda/envs/hf_diff_apf/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hf1/.conda/envs/hf_diff_apf/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hf1/.conda/envs/hf_diff_apf/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hf1/.conda/envs/hf_diff_apf/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 21.54 GiB. GPU 
srun: error: gpu1-cluster3: task 0: Exited with exit code 1
